#build settings
markdown: kramdown
theme: jekyll-theme-cayman

title: "Claudia Hill"
email: claudia@hi-ll.info
description: Finance, Private Banking, Wealth
google_analytics: [Your Google Analytics tracking ID]
